export const EVENT_TYPE_COLORS: Record<string, string> = {
  kingdom: "blue",
  alliance: "green",
  personal: "orange",
  special: "purple",
  kvk: "red",
  ceremony: "gold",
  training: "cyan",
  competitive: "magenta",
  gathering: "lime",
  expedition: "volcano",
  wheel: "geekblue",
  card: "purple",
  power: "red",
  building: "orange",
  research: "blue",
  commander: "cyan",
  troop: "green",
  barbarian: "volcano",
  fort: "magenta",
  resource: "lime",
  vip: "gold",
  recharge: "geekblue",
  alliance_war: "red",
};

export const EVENT_TYPE_TEXTS: Record<string, string> = {
  kingdom: "Toàn Vương Quốc",
  alliance: "Liên Minh",
  personal: "Cá Nhân",
  special: "Đặc Biệt",
  kvk: "KVK",
  ceremony: "Lễ Hội",
  training: "Đào Tạo",
  competitive: "Cạnh Tranh",
  gathering: "Thu Thập",
  expedition: "Thám Hiểm",
  wheel: "Vòng Quay",
  card: "Thẻ Bài",
  power: "Sức Mạnh",
  building: "Xây Dựng",
  research: "Nghiên Cứu",
  commander: "Tướng",
  troop: "Quân Đội",
  barbarian: "Barbarian",
  fort: "Pháo Đài",
  resource: "Tài Nguyên",
  vip: "VIP",
  recharge: "Nạp",
  alliance_war: "Chiến Liên Minh",
};
